// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/avatars/gyoza/concerned-talking.gif"
    | "/avatars/gyoza/concerned.jpeg"
    | "/avatars/gyoza/confused-talking.gif"
    | "/avatars/gyoza/confused.jpeg"
    | "/avatars/gyoza/excited-talking.gif"
    | "/avatars/gyoza/excited.jpeg"
    | "/avatars/gyoza/happy-talking.gif"
    | "/avatars/gyoza/happy.jpeg"
    | "/avatars/gyoza/neutral-talking.gif"
    | "/avatars/gyoza/neutral.jpeg"
    | "/avatars/gyoza/proud-talking.gif"
    | "/avatars/gyoza/proud.jpeg"
    | "/avatars/gyoza/surprised-talking.gif"
    | "/avatars/gyoza/surprised.jpeg"
    | "/avatars/gyoza/thinking-talking.gif"
    | "/avatars/gyoza/thinking.jpeg"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/fonts/CabinetGrotesk-Bold.woff2"
    | "/fonts/CabinetGrotesk-Extrabold.woff2"
    | "/fonts/CabinetGrotesk-Medium.woff2"
    | "/fonts/CabinetGrotesk-Regular.woff2"
    | "/fonts/Satoshi-Bold.woff2"
    | "/fonts/Satoshi-Medium.woff2"
    | "/fonts/Satoshi-Regular.woff2"
    | "/fonts/fonts.css"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-32.png"
    | "/icon-48.png"
    | "/icon-talking.gif"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
